name: Message Slack
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: Log node version
        run: node -v
      - name: Override default container and send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Hello Slack"
          SLACK_CHANNEL: "alerts"
          SLACK_USERNAME: "GitHub Actions"
          SLACK_ICON: https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/OpenMoji-color_1F916.svg/240px-OpenMoji-color_1F916.svg.png
