name: Upload Artifact
on: push

jobs:
  env:
    ARTIFACT_DIR: "artifacts"
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.0.2

      - name: Create directory for artifacts
        run: mkdir -p ${ARTIFACT_DIR}

      - name: Copy files to artifacts directory
        run: cp script.sh ${ARTIFACT_DIR}/

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: my-artifact
          path: ${ARTIFACT_DIR}/
