---
name: On Demand Trigger

on:
  repository_dispatch:
    types: [on-demand-test]

jobs:
  on-demand-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: should run when dispatch api triggerred
        run: |
          echo "trying out on-demand triggers"
          echo "unit: ${{ github.event.client_payload.unit }}"
          echo "integration: ${{ github.event.client_payload.integration }}"
