---
name: Scheduled Trigger

on:
  schedule:
    - cron: "40 11 * * *"
  push:
  pull_request:

jobs:
  scheduled-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: should run on the scheduled cron time (UTC)
        run: |
          echo "trying out scheduled triggers"
          echo "note - for cron schedules: https://crontab.guru"
