---
name: Environment Variables

on: [push, pull_request]
env:
  WF_ENV: this env var is globally available to all jobs
 
jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: this env var is available to log-env jobs
    steps:
      - name: log environment variables
        env:
          STEP_ENV: this env var is available only to this step
        run: |
          echo "(global scope) WF_ENV: ${WF_ENV}"
          echo "(job scope) JOB_ENV: ${JOB_ENV}"
          echo "(step scope) STEP_ENV: ${STEP_ENV}"
      - name: log environment variables 2
        run: |
          echo "(global scope) WF_ENV: ${WF_ENV}"
          echo "(job scope) JOB_ENV: ${JOB_ENV}"
          echo "(step scope) STEP_ENV: ${STEP_ENV}"
          echo "note - STEP_ENV should be out of scope"
  more-log-env:
    runs-on: ubuntu-latest
    steps:
      - name: log environment variables 3
        run: |
          echo "(global scope) WF_ENV: ${WF_ENV}"
          echo "(job scope) JOB_ENV: ${JOB_ENV}"
          echo "(step scope) STEP_ENV: ${STEP_ENV}"
          echo "note - JOB_ENV and STEP_ENV should be out of scope"
