name: Functions
# illustrates GitHub Actions functions

on: push

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: demonstrate various functions
        run: |
          echo demo contains function: ${{ contains('hello', 'll') }}
          echo demo startsWith function: ${{ startsWith('hello', 'he') }}
          echo demo endsWith function: ${{ endsWith('hello', 'lo') }}
          echo demo format function: ${{ format('Hello, {0} {1} {2}', 'World', '!', '!') }}
