name: Conditionals
# illustrates GitHub Actions conditional logic

on: [push, pull_request]

# note: do not need the curly braces to evaluate the 'if' condition
jobs:
  only-push-event:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: only push event
        run: |
          echo 'only run on a push event'
          echo 'event_name:  ${{ github.event_name }}'
  conditions-for-failures:
    runs-on: ubuntu-latest
    steps:
      - name: guaranteed success
        run: |
          echo 'this step is should pass'
      - name: only execute if the previous step succeeded
        if: success()
        run: echo 'the last step was successful'
      - name: always run regardless of the previous step
        if: always()
        run: echo 'this step will always run'
