name: Upload Artifact
on: push

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-linux-script
          path: ./script.sh
